### ISSUE TITLE
Constraint Exception on simple AML query

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#97] opened 2016-01-04 08:10 UTC
Just querying the users, this results in the following error message when switching from "Text" to "Table" view

![image](https://cloud.githubusercontent.com/assets/6908002/12085695/e0138a16-b2c2-11e5-8a08-bf030d5f3901.png)

**Comment by erdomke** [comment] 2016-01-05 00:49
I can't reproduce this in the current release.  If it persists after the update, please re-open the issue.

**Comment by rneuber1** [comment] 2016-01-05 13:40
It still persists:
Run "ApplyAML" with the following query:

 <AML><Item type='User' action='get' maxRecords='10'></Item></AML>

the result appears in the Text View, which becomes the active tab.
Now click on the "Table" tab, the  message below appears:

![image](https://cloud.githubusercontent.com/assets/6908002/12116458/40635a02-b3ba-11e5-8b4a-d3a39cfcac64.png)

**Comment by erdomke** [comment] 2016-01-18 23:36
I re-opened this due to a notification that I finally found on #104.  However, I cannot replicate this in the current version, so I am closing it again.

**Closed by erdomke** 2016-01-18 23:36 UTC
